
import styles from './About.module.css';
export const metadata = {
    title: "about page",
    description: "Generated by create next app",
  };
const AboutPage = () => {
    return (
        <div>
            <h1 className={styles.heading}>this about page</h1>
        </div>
    );
};

export default AboutPage;