import Image from "next/image";
// import nextImg from '../../assets/nextjs.png'; relative path
import nextImg from '@/assets/nextjs.png';

export const metadata = {
    title: "gallery page",
    description: "Generated by create next app",
  };
const GalleryPage = () => {
    
    return (
        <div>
            <h1 className="text-center text-4xl">GalleryPage</h1>
            <h1 className="text-center text-4xl">Regular Image </h1>
            <img className="mx-auto rounded mt-5" src="https://soshace.com/wp-content/uploads/2019/10/Getting-Started-with-NextJS-Inside.jpg" alt="" />
            <h1 className="text-center text-4xl">nextjs image</h1>
            <Image
                className="mx-auto rounded my-5" src="https://soshace.com/wp-content/uploads/2019/10/Getting-Started-with-NextJS-Inside.jpg" alt="next image" 
                width={300}
                height={300}
                // fill={true}
            />
            <h1 className="text-center text-4xl">nextjs local Image</h1>
            <Image
                className="mx-auto rounded mt-5" src={nextImg} alt="next image" 
                width={300}
                height={300}
                // fill={true}
            />
        </div>
    );
};

export default GalleryPage;