// import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "500",
  subsets: ["latin"],
  display: "swap"

});

// metadata works only in server components;

export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
