// "use client"

// import Counter from "@/components/counter/Counter";
export const metadata = {
  title: "home page",
  description: "Generated by create next app",
};

// fetch method works only in server components. it must use async await 
const HomePage = async() => {
  // console.log('hellow browser');
  const res = await fetch("http://localhost:5000/shoes", {
    // cache: "force-cache",
    next: {
      revalidate: 30,
    }
  });
  const shoes =await res.json();
  // console.log(data);
  return (
    <div className="m-10">
      <h1 className='text-3xl'>hellow next js</h1>      
      {/* <Counter></Counter> */}
      <div className="grid grid-cols-3 gap-10 p-5">
        {
          shoes.map(shoe=><div key={shoe.id} className="card card-compact bg-base-100 shadow-xl">
          <figure><img src="https://daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg" alt="Shoes" /></figure>
          <div className="card-body">
          <h2 className="card-title">
            {shoe.title}
            <div className="badge badge-secondary">{shoe.price}</div>
          </h2>
            <p>{shoe.description}</p>
           
            <div className="card-actions justify-end">
            <button className="btn btn-outline btn-primary">Buy Now</button>
              <button className="btn btn-outline btn-primary">Details</button>
            </div>
          </div>
        </div>)
        }
      </div>
    </div>
  );
};

export default HomePage;